name: ottobot
description: A Mattermost bot

dependencies:
  http: "^0.11.3+16"
  html: any
  intl: "^0.15.6"
  logging: "^0.11.3+2"
  mattermost_dart:
    git:
      url: git@github.com:cachapa/mattermost_dart.git
